AC:
    code: AC
    three_letter_code: ASC
AD:
    code: AD
    three_letter_code: AND
    numeric_code: '020'
AE:
    code: AE
    three_letter_code: ARE
    numeric_code: '784'
AF:
    code: AF
    three_letter_code: AFG
    numeric_code: '004'
AG:
    code: AG
    three_letter_code: ATG
    numeric_code: '028'
AI:
    code: AI
    three_letter_code: AIA
    numeric_code: '660'
AL:
    code: AL
    three_letter_code: ALB
    numeric_code: '008'
AM:
    code: AM
    three_letter_code: ARM
    numeric_code: '051'
AN:
    code: AN
    three_letter_code: ANT
    numeric_code: '530'
AO:
    code: AO
    three_letter_code: AGO
    numeric_code: '024'
AQ:
    code: AQ
    three_letter_code: ATA
    numeric_code: '010'
AR:
    code: AR
    three_letter_code: ARG
    numeric_code: '032'
AS:
    code: AS
    three_letter_code: ASM
    numeric_code: '016'
AT:
    code: AT
    three_letter_code: AUT
    numeric_code: '040'
AU:
    code: AU
    three_letter_code: AUS
    numeric_code: '036'
AW:
    code: AW
    three_letter_code: ABW
    numeric_code: '533'
AX:
    code: AX
    three_letter_code: ALA
    numeric_code: '248'
AZ:
    code: AZ
    three_letter_code: AZE
    numeric_code: '031'
BA:
    code: BA
    three_letter_code: BIH
    numeric_code: '070'
BB:
    code: BB
    three_letter_code: BRB
    numeric_code: '052'
BD:
    code: BD
    three_letter_code: BGD
    numeric_code: '050'
BE:
    code: BE
    three_letter_code: BEL
    numeric_code: '056'
BF:
    code: BF
    three_letter_code: BFA
    numeric_code: '854'
BG:
    code: BG
    three_letter_code: BGR
    numeric_code: '100'
BH:
    code: BH
    three_letter_code: BHR
    numeric_code: '048'
BI:
    code: BI
    three_letter_code: BDI
    numeric_code: '108'
BJ:
    code: BJ
    three_letter_code: BEN
    numeric_code: '204'
BL:
    code: BL
    three_letter_code: BLM
    numeric_code: '652'
BM:
    code: BM
    three_letter_code: BMU
    numeric_code: '060'
BN:
    code: BN
    three_letter_code: BRN
    numeric_code: '096'
BO:
    code: BO
    three_letter_code: BOL
    numeric_code: '068'
BQ:
    code: BQ
    three_letter_code: BES
    numeric_code: '535'
BR:
    code: BR
    three_letter_code: BRA
    numeric_code: '076'
BS:
    code: BS
    three_letter_code: BHS
    numeric_code: '044'
BT:
    code: BT
    three_letter_code: BTN
    numeric_code: '064'
BV:
    code: BV
    three_letter_code: BVT
    numeric_code: '074'
BW:
    code: BW
    three_letter_code: BWA
    numeric_code: '072'
BY:
    code: BY
    three_letter_code: BLR
    numeric_code: '112'
BZ:
    code: BZ
    three_letter_code: BLZ
    numeric_code: '084'
CA:
    code: CA
    three_letter_code: CAN
    numeric_code: '124'
CC:
    code: CC
    three_letter_code: CCK
    numeric_code: '166'
CD:
    code: CD
    three_letter_code: COD
    numeric_code: '180'
CF:
    code: CF
    three_letter_code: CAF
    numeric_code: '140'
CG:
    code: CG
    three_letter_code: COG
    numeric_code: '178'
CH:
    code: CH
    three_letter_code: CHE
    numeric_code: '756'
CI:
    code: CI
    three_letter_code: CIV
    numeric_code: '384'
CK:
    code: CK
    three_letter_code: COK
    numeric_code: '184'
CL:
    code: CL
    three_letter_code: CHL
    numeric_code: '152'
CM:
    code: CM
    three_letter_code: CMR
    numeric_code: '120'
CN:
    code: CN
    three_letter_code: CHN
    numeric_code: '156'
CO:
    code: CO
    three_letter_code: COL
    numeric_code: '170'
CP:
    code: CP
    three_letter_code: CPT
CR:
    code: CR
    three_letter_code: CRI
    numeric_code: '188'
CU:
    code: CU
    three_letter_code: CUB
    numeric_code: '192'
CV:
    code: CV
    three_letter_code: CPV
    numeric_code: '132'
CW:
    code: CW
    three_letter_code: CUW
    numeric_code: '531'
CX:
    code: CX
    three_letter_code: CXR
    numeric_code: '162'
CY:
    code: CY
    three_letter_code: CYP
    numeric_code: '196'
CZ:
    code: CZ
    three_letter_code: CZE
    numeric_code: '203'
DE:
    code: DE
    three_letter_code: DEU
    numeric_code: '276'
DG:
    code: DG
    three_letter_code: DGA
DJ:
    code: DJ
    three_letter_code: DJI
    numeric_code: '262'
DK:
    code: DK
    three_letter_code: DNK
    numeric_code: '208'
DM:
    code: DM
    three_letter_code: DMA
    numeric_code: '212'
DO:
    code: DO
    three_letter_code: DOM
    numeric_code: '214'
DZ:
    code: DZ
    three_letter_code: DZA
    numeric_code: '012'
EA:
    code: EA
EC:
    code: EC
    three_letter_code: ECU
    numeric_code: '218'
EE:
    code: EE
    three_letter_code: EST
    numeric_code: '233'
EG:
    code: EG
    three_letter_code: EGY
    numeric_code: '818'
EH:
    code: EH
    three_letter_code: ESH
    numeric_code: '732'
ER:
    code: ER
    three_letter_code: ERI
    numeric_code: '232'
ES:
    code: ES
    three_letter_code: ESP
    numeric_code: '724'
ET:
    code: ET
    three_letter_code: ETH
    numeric_code: '231'
FI:
    code: FI
    three_letter_code: FIN
    numeric_code: '246'
FJ:
    code: FJ
    three_letter_code: FJI
    numeric_code: '242'
FK:
    code: FK
    three_letter_code: FLK
    numeric_code: '238'
FM:
    code: FM
    three_letter_code: FSM
    numeric_code: '583'
FO:
    code: FO
    three_letter_code: FRO
    numeric_code: '234'
FR:
    code: FR
    three_letter_code: FRA
    numeric_code: '250'
GA:
    code: GA
    three_letter_code: GAB
    numeric_code: '266'
GB:
    code: GB
    three_letter_code: GBR
    numeric_code: '826'
GD:
    code: GD
    three_letter_code: GRD
    numeric_code: '308'
GE:
    code: GE
    three_letter_code: GEO
    numeric_code: '268'
GF:
    code: GF
    three_letter_code: GUF
    numeric_code: '254'
GG:
    code: GG
    three_letter_code: GGY
    numeric_code: '831'
GH:
    code: GH
    three_letter_code: GHA
    numeric_code: '288'
GI:
    code: GI
    three_letter_code: GIB
    numeric_code: '292'
GL:
    code: GL
    three_letter_code: GRL
    numeric_code: '304'
GM:
    code: GM
    three_letter_code: GMB
    numeric_code: '270'
GN:
    code: GN
    three_letter_code: GIN
    numeric_code: '324'
GP:
    code: GP
    three_letter_code: GLP
    numeric_code: '312'
GQ:
    code: GQ
    three_letter_code: GNQ
    numeric_code: '226'
GR:
    code: GR
    three_letter_code: GRC
    numeric_code: '300'
GS:
    code: GS
    three_letter_code: SGS
    numeric_code: '239'
GT:
    code: GT
    three_letter_code: GTM
    numeric_code: '320'
GU:
    code: GU
    three_letter_code: GUM
    numeric_code: '316'
GW:
    code: GW
    three_letter_code: GNB
    numeric_code: '624'
GY:
    code: GY
    three_letter_code: GUY
    numeric_code: '328'
HK:
    code: HK
    three_letter_code: HKG
    numeric_code: '344'
HM:
    code: HM
    three_letter_code: HMD
    numeric_code: '334'
HN:
    code: HN
    three_letter_code: HND
    numeric_code: '340'
HR:
    code: HR
    three_letter_code: HRV
    numeric_code: '191'
HT:
    code: HT
    three_letter_code: HTI
    numeric_code: '332'
HU:
    code: HU
    three_letter_code: HUN
    numeric_code: '348'
IC:
    code: IC
ID:
    code: ID
    three_letter_code: IDN
    numeric_code: '360'
IE:
    code: IE
    three_letter_code: IRL
    numeric_code: '372'
IL:
    code: IL
    three_letter_code: ISR
    numeric_code: '376'
IM:
    code: IM
    three_letter_code: IMN
    numeric_code: '833'
IN:
    code: IN
    three_letter_code: IND
    numeric_code: '356'
IO:
    code: IO
    three_letter_code: IOT
    numeric_code: '086'
IQ:
    code: IQ
    three_letter_code: IRQ
    numeric_code: '368'
IR:
    code: IR
    three_letter_code: IRN
    numeric_code: '364'
IS:
    code: IS
    three_letter_code: ISL
    numeric_code: '352'
IT:
    code: IT
    three_letter_code: ITA
    numeric_code: '380'
JE:
    code: JE
    three_letter_code: JEY
    numeric_code: '832'
JM:
    code: JM
    three_letter_code: JAM
    numeric_code: '388'
JO:
    code: JO
    three_letter_code: JOR
    numeric_code: '400'
JP:
    code: JP
    three_letter_code: JPN
    numeric_code: '392'
KE:
    code: KE
    three_letter_code: KEN
    numeric_code: '404'
KG:
    code: KG
    three_letter_code: KGZ
    numeric_code: '417'
KH:
    code: KH
    three_letter_code: KHM
    numeric_code: '116'
KI:
    code: KI
    three_letter_code: KIR
    numeric_code: '296'
KM:
    code: KM
    three_letter_code: COM
    numeric_code: '174'
KN:
    code: KN
    three_letter_code: KNA
    numeric_code: '659'
KP:
    code: KP
    three_letter_code: PRK
    numeric_code: '408'
KR:
    code: KR
    three_letter_code: KOR
    numeric_code: '410'
KW:
    code: KW
    three_letter_code: KWT
    numeric_code: '414'
KY:
    code: KY
    three_letter_code: CYM
    numeric_code: '136'
KZ:
    code: KZ
    three_letter_code: KAZ
    numeric_code: '398'
LA:
    code: LA
    three_letter_code: LAO
    numeric_code: '418'
LB:
    code: LB
    three_letter_code: LBN
    numeric_code: '422'
LC:
    code: LC
    three_letter_code: LCA
    numeric_code: '662'
LI:
    code: LI
    three_letter_code: LIE
    numeric_code: '438'
LK:
    code: LK
    three_letter_code: LKA
    numeric_code: '144'
LR:
    code: LR
    three_letter_code: LBR
    numeric_code: '430'
LS:
    code: LS
    three_letter_code: LSO
    numeric_code: '426'
LT:
    code: LT
    three_letter_code: LTU
    numeric_code: '440'
LU:
    code: LU
    three_letter_code: LUX
    numeric_code: '442'
LV:
    code: LV
    three_letter_code: LVA
    numeric_code: '428'
LY:
    code: LY
    three_letter_code: LBY
    numeric_code: '434'
MA:
    code: MA
    three_letter_code: MAR
    numeric_code: '504'
MC:
    code: MC
    three_letter_code: MCO
    numeric_code: '492'
MD:
    code: MD
    three_letter_code: MDA
    numeric_code: '498'
ME:
    code: ME
    three_letter_code: MNE
    numeric_code: '499'
MF:
    code: MF
    three_letter_code: MAF
    numeric_code: '663'
MG:
    code: MG
    three_letter_code: MDG
    numeric_code: '450'
MH:
    code: MH
    three_letter_code: MHL
    numeric_code: '584'
MK:
    code: MK
    three_letter_code: MKD
    numeric_code: '807'
ML:
    code: ML
    three_letter_code: MLI
    numeric_code: '466'
MM:
    code: MM
    three_letter_code: MMR
    numeric_code: '104'
MN:
    code: MN
    three_letter_code: MNG
    numeric_code: '496'
MO:
    code: MO
    three_letter_code: MAC
    numeric_code: '446'
MP:
    code: MP
    three_letter_code: MNP
    numeric_code: '580'
MQ:
    code: MQ
    three_letter_code: MTQ
    numeric_code: '474'
MR:
    code: MR
    three_letter_code: MRT
    numeric_code: '478'
MS:
    code: MS
    three_letter_code: MSR
    numeric_code: '500'
MT:
    code: MT
    three_letter_code: MLT
    numeric_code: '470'
MU:
    code: MU
    three_letter_code: MUS
    numeric_code: '480'
MV:
    code: MV
    three_letter_code: MDV
    numeric_code: '462'
MW:
    code: MW
    three_letter_code: MWI
    numeric_code: '454'
MX:
    code: MX
    three_letter_code: MEX
    numeric_code: '484'
MY:
    code: MY
    three_letter_code: MYS
    numeric_code: '458'
MZ:
    code: MZ
    three_letter_code: MOZ
    numeric_code: '508'
NA:
    code: NA
    three_letter_code: NAM
    numeric_code: '516'
NC:
    code: NC
    three_letter_code: NCL
    numeric_code: '540'
NE:
    code: NE
    three_letter_code: NER
    numeric_code: '562'
NF:
    code: NF
    three_letter_code: NFK
    numeric_code: '574'
NG:
    code: NG
    three_letter_code: NGA
    numeric_code: '566'
NI:
    code: NI
    three_letter_code: NIC
    numeric_code: '558'
NL:
    code: NL
    three_letter_code: NLD
    numeric_code: '528'
NO:
    code: NO
    three_letter_code: NOR
    numeric_code: '578'
NP:
    code: NP
    three_letter_code: NPL
    numeric_code: '524'
NR:
    code: NR
    three_letter_code: NRU
    numeric_code: '520'
NU:
    code: NU
    three_letter_code: NIU
    numeric_code: '570'
NZ:
    code: NZ
    three_letter_code: NZL
    numeric_code: '554'
OM:
    code: OM
    three_letter_code: OMN
    numeric_code: '512'
PA:
    code: PA
    three_letter_code: PAN
    numeric_code: '591'
PE:
    code: PE
    three_letter_code: PER
    numeric_code: '604'
PF:
    code: PF
    three_letter_code: PYF
    numeric_code: '258'
PG:
    code: PG
    three_letter_code: PNG
    numeric_code: '598'
PH:
    code: PH
    three_letter_code: PHL
    numeric_code: '608'
PK:
    code: PK
    three_letter_code: PAK
    numeric_code: '586'
PL:
    code: PL
    three_letter_code: POL
    numeric_code: '616'
PM:
    code: PM
    three_letter_code: SPM
    numeric_code: '666'
PN:
    code: PN
    three_letter_code: PCN
    numeric_code: '612'
PR:
    code: PR
    three_letter_code: PRI
    numeric_code: '630'
PS:
    code: PS
    three_letter_code: PSE
    numeric_code: '275'
PT:
    code: PT
    three_letter_code: PRT
    numeric_code: '620'
PW:
    code: PW
    three_letter_code: PLW
    numeric_code: '585'
PY:
    code: PY
    three_letter_code: PRY
    numeric_code: '600'
QA:
    code: QA
    three_letter_code: QAT
    numeric_code: '634'
QO:
    code: QO
    three_letter_code: QOO
    numeric_code: '961'
RE:
    code: RE
    three_letter_code: REU
    numeric_code: '638'
RO:
    code: RO
    three_letter_code: ROU
    numeric_code: '642'
RS:
    code: RS
    three_letter_code: SRB
    numeric_code: '688'
RU:
    code: RU
    three_letter_code: RUS
    numeric_code: '643'
RW:
    code: RW
    three_letter_code: RWA
    numeric_code: '646'
SA:
    code: SA
    three_letter_code: SAU
    numeric_code: '682'
SB:
    code: SB
    three_letter_code: SLB
    numeric_code: '090'
SC:
    code: SC
    three_letter_code: SYC
    numeric_code: '690'
SD:
    code: SD
    three_letter_code: SDN
    numeric_code: '729'
SE:
    code: SE
    three_letter_code: SWE
    numeric_code: '752'
SG:
    code: SG
    three_letter_code: SGP
    numeric_code: '702'
SH:
    code: SH
    three_letter_code: SHN
    numeric_code: '654'
SI:
    code: SI
    three_letter_code: SVN
    numeric_code: '705'
SJ:
    code: SJ
    three_letter_code: SJM
    numeric_code: '744'
SK:
    code: SK
    three_letter_code: SVK
    numeric_code: '703'
SL:
    code: SL
    three_letter_code: SLE
    numeric_code: '694'
SM:
    code: SM
    three_letter_code: SMR
    numeric_code: '674'
SN:
    code: SN
    three_letter_code: SEN
    numeric_code: '686'
SO:
    code: SO
    three_letter_code: SOM
    numeric_code: '706'
SR:
    code: SR
    three_letter_code: SUR
    numeric_code: '740'
SS:
    code: SS
    three_letter_code: SSD
    numeric_code: '728'
ST:
    code: ST
    three_letter_code: STP
    numeric_code: '678'
SV:
    code: SV
    three_letter_code: SLV
    numeric_code: '222'
SX:
    code: SX
    three_letter_code: SXM
    numeric_code: '534'
SY:
    code: SY
    three_letter_code: SYR
    numeric_code: '760'
SZ:
    code: SZ
    three_letter_code: SWZ
    numeric_code: '748'
TA:
    code: TA
    three_letter_code: TAA
TC:
    code: TC
    three_letter_code: TCA
    numeric_code: '796'
TD:
    code: TD
    three_letter_code: TCD
    numeric_code: '148'
TF:
    code: TF
    three_letter_code: ATF
    numeric_code: '260'
TG:
    code: TG
    three_letter_code: TGO
    numeric_code: '768'
TH:
    code: TH
    three_letter_code: THA
    numeric_code: '764'
TJ:
    code: TJ
    three_letter_code: TJK
    numeric_code: '762'
TK:
    code: TK
    three_letter_code: TKL
    numeric_code: '772'
TL:
    code: TL
    three_letter_code: TLS
    numeric_code: '626'
TM:
    code: TM
    three_letter_code: TKM
    numeric_code: '795'
TN:
    code: TN
    three_letter_code: TUN
    numeric_code: '788'
TO:
    code: TO
    three_letter_code: TON
    numeric_code: '776'
TR:
    code: TR
    three_letter_code: TUR
    numeric_code: '792'
TT:
    code: TT
    three_letter_code: TTO
    numeric_code: '780'
TV:
    code: TV
    three_letter_code: TUV
    numeric_code: '798'
TW:
    code: TW
    three_letter_code: TWN
    numeric_code: '158'
TZ:
    code: TZ
    three_letter_code: TZA
    numeric_code: '834'
UA:
    code: UA
    three_letter_code: UKR
    numeric_code: '804'
UG:
    code: UG
    three_letter_code: UGA
    numeric_code: '800'
UM:
    code: UM
    three_letter_code: UMI
    numeric_code: '581'
US:
    code: US
    three_letter_code: USA
    numeric_code: '840'
UY:
    code: UY
    three_letter_code: URY
    numeric_code: '858'
UZ:
    code: UZ
    three_letter_code: UZB
    numeric_code: '860'
VA:
    code: VA
    three_letter_code: VAT
    numeric_code: '336'
VC:
    code: VC
    three_letter_code: VCT
    numeric_code: '670'
VE:
    code: VE
    three_letter_code: VEN
    numeric_code: '862'
VG:
    code: VG
    three_letter_code: VGB
    numeric_code: '092'
VI:
    code: VI
    three_letter_code: VIR
    numeric_code: '850'
VN:
    code: VN
    three_letter_code: VNM
    numeric_code: '704'
VU:
    code: VU
    three_letter_code: VUT
    numeric_code: '548'
WF:
    code: WF
    three_letter_code: WLF
    numeric_code: '876'
WS:
    code: WS
    three_letter_code: WSM
    numeric_code: '882'
XK:
    code: XK
    three_letter_code: XKK
    numeric_code: '983'
YE:
    code: YE
    three_letter_code: YEM
    numeric_code: '887'
YT:
    code: YT
    three_letter_code: MYT
    numeric_code: '175'
ZA:
    code: ZA
    three_letter_code: ZAF
    numeric_code: '710'
ZM:
    code: ZM
    three_letter_code: ZMB
    numeric_code: '894'
ZW:
    code: ZW
    three_letter_code: ZWE
    numeric_code: '716'
